version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Looks for package.json and lock file in root
    schedule:
      interval: "daily"
    target-branch: "preview"
    versioning-strategy: widen
    commit-message:
      prefix: "deps"
      include: "scope"